// ---------------------------------------------------------------------------
// Affiliate settings
// Replace AMAZON_TAG with your Amazon Associates tracking ID (ends in -21 for amazon.co.uk).
// For any product, set `asin` to link straight to a product page instead of a search.
// ---------------------------------------------------------------------------
const AMAZON_TAG = "readyhomeuk-21";

const CATEGORIES = [
  { id: "all", label: "Everything" },
  { id: "safety", label: "Safety & PPE" },
  { id: "cab", label: "Cab living" },
  { id: "food", label: "Food & drink" },
  { id: "tech", label: "Tech & power" },
  { id: "security", label: "Load & cab security" },
  { id: "europe", label: "Driving in Europe" },
  { id: "winter", label: "Winter" },
  { id: "health", label: "Health & comfort" },
];

// Helpers used in quantity text. `h` = { nights, drivers, europe, winter }.
// nights = nights out in a row; drivers = 1 or 2 (double-manned); europe/winter = 0 or 1.
const days = (h) => h.nights + 1;
const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;
const each = (h, one, many) => (h.drivers === 1 ? `1 ${one}` : `${h.drivers} ${many}, one each`);

const PRODUCTS = [
  // ---- Safety & PPE --------------------------------------------------------
  {
    id: "hivis",
    name: "Hi-vis vest or jacket",
    category: "safety",
    official: true,
    summary: "Required on most yards and sites, and by law in most European countries if you stop on the roadside.",
    why: "Almost every distribution centre, port and quarry will turn you away without hi-vis. In France, Spain, Italy, Belgium, Austria and many other countries you must also have one within reach in the cab, not in a locker, and put it on before you step out after a breakdown.",
    lookFor: [
      "Marked EN ISO 20471, Class 2 or Class 3",
      "Keep one in the door pocket so you can reach it before getting out",
      "A long-sleeve hi-vis jacket covers you at sites that ask for arms covered",
    ],
    qty: (h) => `${plural(h.drivers * 2, "vest", "vests")}: one to wear, one spare`,
    query: "hi vis vest EN ISO 20471 class 2 pack",
  },
  {
    id: "boots",
    name: "Safety boots",
    category: "safety",
    official: false,
    summary: "Steel or composite toe caps. Most yards won't let you out of the cab without them.",
    why: "Pallets, trolleys, kingpins and landing legs are all heavy enough to break a foot. Most sites require S3 safety boots, and a comfortable pair matters when you're climbing in and out of the cab dozens of times a day.",
    lookFor: [
      "S3 rating: toe cap, midsole protection and water resistance",
      "Composite toe caps are lighter and don't conduct cold",
      "Good grip on wet steps and trailer beds",
    ],
    qty: (h) => each(h, "pair", "pairs"),
    query: "S3 safety boots composite toe men",
  },
  {
    id: "gloves",
    name: "Work gloves",
    category: "safety",
    official: false,
    summary: "For straps, curtains, fifth wheels and diesel. Keep a few pairs, they wear fast.",
    why: "Coupling up, ratcheting straps and pulling curtains are hard on the hands. Grippy, cut-resistant gloves stop cuts and splinters, and a box of disposable nitrile gloves keeps diesel and grease off your skin when refuelling or checking oil.",
    lookFor: [
      "Nitrile-coated knitted gloves for grip and dexterity",
      "Cut level B or higher if you handle sheet metal or glass",
      "A box of disposable nitrile gloves for refuelling",
    ],
    qty: (h) => `${plural(h.drivers * 6, "pair", "pairs")} of work gloves, plus a box of disposables`,
    query: "nitrile coated work gloves 12 pairs",
  },
  {
    id: "headtorch",
    name: "Rechargeable head torch",
    category: "safety",
    official: false,
    summary: "Hands-free light for walk-round checks, coupling up and dark yards at night.",
    why: "Your daily walk-round check, coupling and uncoupling, and finding a fault on a dark lay-by all need two hands. A bright head torch is one of the most-used bits of kit in any cab.",
    lookFor: [
      "USB-C rechargeable, so you can charge it in the cab",
      "At least 300 lumens, with a red light mode for inside the cab",
      "Waterproof to IPX4 or better",
    ],
    qty: (h) => each(h, "head torch", "head torches"),
    query: "rechargeable head torch USB C 1000 lumen",
  },
  {
    id: "firstaid",
    name: "Vehicle first aid kit",
    category: "safety",
    official: true,
    summary: "A proper kit, not a handful of plasters. Required by law in some countries, such as Germany and Austria.",
    why: "You could be the first person at a motorway crash, or cut yourself on a strap miles from anywhere. Some European countries, including Germany and Austria, require vehicles to carry a first aid kit, and many operators insist on one in every cab.",
    lookFor: [
      "Marked DIN 13164, the German standard accepted across Europe",
      "Includes gloves, a foil blanket, large dressings and a face shield",
      "Check the dates once a year and replace anything you've used",
    ],
    qty: () => "1 per cab",
    query: "DIN 13164 vehicle first aid kit",
  },
  {
    id: "triangle",
    name: "Warning triangle",
    category: "safety",
    official: true,
    summary: "Required in most European countries. Many trucks don't have one fitted.",
    why: "Most European countries require you to carry a warning triangle and put it out behind the vehicle after a breakdown or crash. On UK motorways it isn't recommended, because walking back to place it is dangerous, but you'll need one as soon as you cross the Channel.",
    lookFor: [
      "Marked ECE R27",
      "A heavy, weighted base that won't blow over in the wind from passing trucks",
      "Some countries ask for two; check your route",
    ],
    qty: () => "1 per vehicle (some countries ask for 2)",
    query: "warning triangle ECE R27 heavy duty",
  },
  {
    id: "extinguisher",
    name: "Fire extinguisher",
    category: "safety",
    official: false,
    summary: "A 1–2kg powder extinguisher can stop a small cab or tyre fire spreading to the load.",
    why: "Brake and tyre fires, electrical faults and night heaters can all start fires. Many operators require an extinguisher in the cab, and ADR (dangerous goods) loads need specific sizes. Only tackle a fire if it's small and you have a way out.",
    lookFor: [
      "1kg or 2kg ABC dry powder, with a vehicle mounting bracket",
      "For ADR loads, follow the sizes your operator's ADR rules set out",
      "Check the pressure gauge is in the green every month",
    ],
    qty: () => "1 per cab",
    query: "2kg dry powder fire extinguisher vehicle bracket",
  },
  {
    id: "coalarm",
    name: "Carbon monoxide alarm",
    category: "safety",
    official: false,
    summary: "Essential if you run a night heater. Carbon monoxide has no smell.",
    why: "Diesel night heaters are safe when working properly, but a damaged exhaust or a cab parked against a wall or snowbank can let carbon monoxide in while you sleep. A small battery alarm on the bunk shelf wakes you up before it becomes dangerous.",
    lookFor: [
      "Battery powered, with a 7 or 10-year sealed battery",
      "Marked EN 50291, the European standard",
      "Mount it near where you sleep, not right next to the heater outlet",
    ],
    qty: () => "1 per sleeper cab",
    showWhen: (h) => h.nights > 0,
    query: "portable carbon monoxide alarm EN 50291 10 year battery",
  },
  {
    id: "tyregauge",
    name: "Truck tyre pressure gauge",
    category: "safety",
    official: false,
    summary: "Check your tyres properly on the daily walk-round, not just by kicking them.",
    why: "Under-inflated tyres overheat, wear unevenly and burn more fuel, and a blowout at speed is one of the most dangerous things that can happen in a truck. A dual-head gauge reaches the inner valves on twin wheels.",
    lookFor: [
      "Dual-head (push-pull) chuck to reach inner twin wheels",
      "Reads up to at least 150 psi (10 bar)",
      "A tyre tread depth gauge is a cheap, useful extra",
    ],
    qty: () => "1 per cab",
    query: "truck tyre pressure gauge dual head 150 psi",
  },

  // ---- Cab living ----------------------------------------------------------
  {
    id: "sleepingbag",
    name: "Sleeping bag or bunk duvet",
    category: "cab",
    official: false,
    summary: "A proper night's sleep is the best safety equipment you can own.",
    why: "Fatigue is a factor in many serious truck crashes. A warm, comfortable bunk makes a real difference to how rested you are, especially in winter if you want to save fuel by not running the night heater all night. A duvet in a stuff sack packs away during the day.",
    lookFor: [
      "A rectangular bag that opens out into a duvet for milder nights",
      "Rated comfortable to around 0°C if you sleep without the heater",
      "Washable, with a cover or liner you can swap",
    ],
    qty: (h) => each(h, "sleeping bag", "sleeping bags"),
    showWhen: (h) => h.nights > 0,
    query: "rectangular sleeping bag 3 season washable",
  },
  {
    id: "pillow",
    name: "Memory foam pillow",
    category: "cab",
    official: false,
    summary: "Bunk mattresses are thin. A good pillow helps you sleep and wake without a stiff neck.",
    why: "Sleeping in the cab several nights a week takes a toll on your neck and back. A supportive pillow, plus a mattress topper if your bunk is hard, is a cheap upgrade you'll feel every morning.",
    lookFor: [
      "Memory foam with a removable, washable cover",
      "A bunk mattress topper (usually 70cm wide) if your mattress is worn",
      "A vacuum bag keeps bedding compact during the day",
    ],
    qty: (h) => each(h, "pillow", "pillows"),
    showWhen: (h) => h.nights > 0,
    query: "memory foam pillow washable cover",
  },
  {
    id: "sleepmask",
    name: "Eye mask and ear plugs",
    category: "cab",
    official: false,
    summary: "Truck stops are noisy and bright. Block out fridge units, engines and floodlights.",
    why: "Reefer units, idling engines and floodlit parking make it hard to get a full rest. A contoured eye mask and good foam ear plugs are the cheapest way to sleep better on a night out.",
    lookFor: [
      "A contoured mask that doesn't press on your eyes",
      "Foam ear plugs rated SNR 33dB or higher",
      "Keep your phone alarm loud enough to hear through them",
    ],
    qty: (h) => each(h, "set", "sets"),
    showWhen: (h) => h.nights > 0,
    query: "contoured sleep mask ear plugs set",
  },
  {
    id: "fan",
    name: "24V cab fan",
    category: "cab",
    official: false,
    summary: "Keeps the bunk bearable on hot nights without idling the engine.",
    why: "Idling to run the air-con wastes fuel, is banned in many places and annoys everyone around you. A small 24V fan on the bunk shelf moves enough air to sleep on a warm summer night in southern Europe.",
    lookFor: [
      "24V rated, or USB powered with a 24V USB charger",
      "Clip-on or with a mounting bracket so it doesn't slide around",
      "Quiet, with more than one speed",
    ],
    qty: () => "1 per sleeper cab",
    showWhen: (h) => h.nights > 0,
    query: "24v fan truck clip on",
  },
  {
    id: "toiletries",
    name: "Wash bag and shower kit",
    category: "cab",
    official: false,
    summary: "A hanging wash bag that's ready to grab on the way to the truck stop shower.",
    why: "Truck stop showers are often a long walk across the car park. A hanging wash bag with everything in it, from shower gel to a toothbrush, means you're in and out quickly. Pack some no-rinse wipes for nights with no showers at all.",
    lookFor: [
      "A hanging bag with a hook for shower cubicles",
      "Travel-size bottles you can refill from big ones in the cab",
      "Body wipes or no-rinse shower wipes for nights with no facilities",
    ],
    qty: (h) => each(h, "wash bag", "wash bags"),
    showWhen: (h) => h.nights > 0,
    query: "hanging toiletry bag men",
  },
  {
    id: "towel",
    name: "Microfibre towel",
    category: "cab",
    official: false,
    summary: "Dries fast and packs small, so it doesn't stay damp in the cab.",
    why: "A normal cotton towel stays damp and smells within days in a closed cab. A microfibre travel towel dries in a couple of hours hung over the seat.",
    lookFor: [
      "Large or extra-large size (around 75 × 150cm)",
      "Comes with a mesh bag so it can breathe",
      "Two, so one can dry while you use the other",
    ],
    qty: (h) => `${plural(h.drivers * 2, "towel", "towels")}`,
    showWhen: (h) => h.nights > 0,
    query: "microfibre travel towel large",
  },
  {
    id: "flipflops",
    name: "Shower flip-flops",
    category: "cab",
    official: false,
    summary: "Never shower barefoot at a truck stop.",
    why: "Shared showers are a common place to pick up athlete's foot and verrucas. Cheap pool sliders or flip-flops take up no room and save a lot of discomfort.",
    lookFor: ["Quick-drying rubber or EVA", "Sliders are easier to slip on in a hurry"],
    qty: (h) => each(h, "pair", "pairs"),
    showWhen: (h) => h.nights > 0,
    query: "pool sliders men",
  },
  {
    id: "sanitiser",
    name: "Hand sanitiser and wipes",
    category: "cab",
    official: false,
    summary: "For when there's no sink: after refuelling, coupling up or using a lay-by.",
    why: "Many delivery points and lay-bys have no washing facilities. Keep hand sanitiser and a tub of heavy-duty wipes in the door pocket for diesel, grease and before eating.",
    lookFor: [
      "At least 60% alcohol sanitiser",
      "Heavy-duty trade wipes shift diesel and grease",
      "A roll of blue paper towel is useful too",
    ],
    qty: () => "1 bottle of sanitiser and 1 tub of wipes per cab",
    query: "heavy duty trade wipes hand sanitiser",
  },

  // ---- Food & drink --------------------------------------------------------
  {
    id: "coolbox",
    name: "12/24V electric cool box",
    category: "food",
    official: false,
    summary: "Bring food from home and save £10–£15 a day on truck stop meals.",
    why: "Eating out every meal on the road gets expensive and unhealthy. A cool box that runs on the truck's 24V supply keeps a few days of food fresh, and a compressor model works like a small fridge even in summer.",
    lookFor: [
      "Runs on 24V (most trucks) as well as 12V; check before you buy",
      "Compressor models cool properly in hot weather; thermoelectric ones are cheaper but weaker",
      "Battery protection, so it can't flatten the truck batteries overnight",
    ],
    qty: (h) => (h.nights > 2 ? "1 compressor cool box, 25–35 litres" : "1 cool box, 20–25 litres"),
    query: "12v 24v compressor cool box truck",
  },
  {
    id: "kettle",
    name: "24V kettle",
    category: "food",
    official: false,
    summary: "A hot drink or pot noodle in the cab, without walking to the services.",
    why: "A kettle that runs from the truck's 24V socket means tea, coffee and simple hot meals wherever you're parked. It takes longer than a mains kettle, so fill it before you stop.",
    lookFor: [
      "Rated 24V, not 12V: a 12V kettle won't work safely on a 24V truck",
      "Plugs into the cigarette lighter socket (check its fuse rating)",
      "Auto shut-off when it boils",
    ],
    qty: () => "1 per cab",
    query: "24v kettle truck",
  },
  {
    id: "lunchheater",
    name: "24V lunch box heater",
    category: "food",
    official: false,
    summary: "Heats a home-cooked meal in about 30–45 minutes while you drive.",
    why: "An electric lunch box warms leftovers or a ready meal while you're on the road, so it's hot by your break. It's the closest thing to a microwave you can safely run in most cabs.",
    lookFor: [
      "24V and 230V leads, so it also works at home or the depot",
      "A removable stainless steel tray that's easy to clean",
      "At least 1.5 litres for a proper meal",
    ],
    qty: () => "1 per cab",
    query: "24v electric lunch box heater truck",
  },
  {
    id: "flask",
    name: "Vacuum flask",
    category: "food",
    official: false,
    summary: "Hot drinks for hours. Fill it up whenever you pass a good coffee machine.",
    why: "A stainless steel flask keeps coffee or soup hot for 12 hours or more, so you always have a hot drink on your break even when you're parked somewhere with nothing nearby.",
    lookFor: [
      "Stainless steel, double-walled, around 1 litre",
      "A cup lid plus a pour-through stopper",
      "A smaller travel mug that fits the cab's cup holder",
    ],
    qty: (h) => each(h, "flask", "flasks"),
    query: "stainless steel vacuum flask 1 litre",
  },
  {
    id: "water",
    name: "Bottled water",
    category: "food",
    official: false,
    summary: "Stay hydrated. Tired, dehydrated drivers make mistakes.",
    why: "Many drivers drink less to avoid toilet stops, but dehydration causes headaches and tiredness, and slows your reactions. Aim for around 2–3 litres a day, more in hot weather or if you're handballing loads.",
    lookFor: [
      "A pack of 1.5L bottles stays in the cab for emergencies, too",
      "A large reusable bottle you refill from home or at the depot",
      "Electrolyte tablets in hot weather",
    ],
    qty: (h) => `${3 * days(h) * h.drivers} litres for the trip (3 litres a day each)`,
    query: "bottled water 1.5 litre pack",
  },
  {
    id: "snacks",
    name: "Healthy long-life snacks",
    category: "food",
    official: false,
    summary: "Nuts, oat bars and dried fruit, so you're not living on service station sweets.",
    why: "Long, irregular shifts make it easy to snack badly. A stash of filling, slow-release snacks keeps your energy level steady through a long day and helps if you get stuck in a queue at the port or a closed motorway.",
    lookFor: [
      "Unsalted mixed nuts, oat bars, protein bars and dried fruit",
      "Things that won't melt in a hot cab",
      "Enough for at least one extra day, in case you're delayed",
    ],
    qty: (h) => `${plural(2 * (days(h) + 1) * h.drivers, "snack", "snacks")}, including a spare day`,
    query: "mixed nuts snack packs",
  },

  // ---- Tech & power --------------------------------------------------------
  {
    id: "satnav",
    name: "Truck sat nav",
    category: "tech",
    official: false,
    summary: "Routes around low bridges, weight limits and narrow roads. A phone app isn't enough.",
    why: "A car sat nav or phone map doesn't know your height, weight or width, and bridge strikes happen in the UK every day. A truck sat nav lets you enter your vehicle's size and plans routes that avoid low bridges, weak bridges and banned roads, across the UK and Europe.",
    lookFor: [
      "Lets you enter height, width, length, weight and hazardous loads",
      "Free lifetime maps for the UK and Europe",
      "A screen of at least 7 inches you can read at a glance",
      "Still check the height on every bridge sign: you are responsible",
    ],
    qty: () => "1 per cab",
    query: "truck sat nav 7 inch UK Europe maps",
    buyLabel: "Truck sat navs on Amazon UK",
  },
  {
    id: "dashcam",
    name: "Dash cam",
    category: "tech",
    official: false,
    summary: "Video evidence for crashes, cash-for-crash scams and insurance claims.",
    why: "When a car pulls in front of a truck and brakes, it's often the truck driver who gets blamed. Front and rear footage protects your licence and your job, and some insurers and operators require it.",
    lookFor: [
      "At least 1440p front camera with good night vision",
      "Front and rear, or a 3-channel kit that also covers the cab",
      "Hardwired or 24V compatible, with a parking mode",
    ],
    qty: () => "1 per cab",
    query: "front and rear dash cam 24v truck",
  },
  {
    id: "charger",
    name: "24V USB charger",
    category: "tech",
    official: false,
    summary: "Fast charging for your phone, sat nav and tablet from the truck's 24V socket.",
    why: "Many cheap car chargers only work on 12V and can fail or overheat on a truck's 24V system. A charger rated 12–24V with USB-C fast charging keeps your phone ready for calls, tachograph apps and navigation.",
    lookFor: [
      "Rated 12–24V",
      "At least one USB-C port with Power Delivery (30W or more)",
      "Spare, longer cables to reach the bunk",
    ],
    qty: () => "1 per cab, plus 2 long cables",
    query: "12v 24v usb c car charger PD fast charge",
  },
  {
    id: "powerbank",
    name: "Power bank",
    category: "tech",
    official: false,
    summary: "Keeps your phone charged when the engine's off or you're away from the cab.",
    why: "When you're on a ferry, in a queue at a port, or resting with the engine off, a power bank keeps your phone alive. It's also handy at the bunk if your charging socket is out of reach.",
    lookFor: [
      "20,000 mAh for several full phone charges",
      "USB-C in and out, so one cable does both",
      "Under 100Wh, so it's allowed on ferries and flights",
    ],
    qty: (h) => each(h, "power bank", "power banks"),
    query: "power bank 20000mAh USB C",
  },
  {
    id: "phonemount",
    name: "Phone holder",
    category: "tech",
    official: false,
    summary: "It's illegal to hold your phone while driving. A fixed mount keeps it hands-free.",
    why: "Holding a phone while driving costs 6 points and a £200 fine in the UK, and for an HGV driver it can mean your licence and job. A secure mount lets you use navigation or answer hands-free calls legally, as long as it doesn't block your view.",
    lookFor: [
      "A strong suction or vent mount that won't drop on rough roads",
      "Positioned so it doesn't block your view of the road or mirrors",
      "Wireless charging is a handy extra",
    ],
    qty: () => "1 per cab",
    query: "dashboard phone holder suction strong truck",
  },
  {
    id: "inverter",
    name: "24V to 230V inverter",
    category: "tech",
    official: false,
    summary: "Run a laptop or charge tools from a normal UK plug socket in the cab.",
    why: "An inverter turns the truck's 24V supply into a normal 230V socket, for laptops, a small TV or a shaver. Pick a pure sine wave model for anything sensitive, and remember it drains the batteries quickly with the engine off.",
    lookFor: [
      "24V input (a 12V inverter won't work on most trucks)",
      "Pure sine wave, 300–1000W, depending on what you'll run",
      "Low-voltage cut-off, so you can still start the truck",
    ],
    qty: () => "1 per cab",
    query: "24v to 230v pure sine wave inverter",
  },
  {
    id: "cbradio",
    name: "CB radio",
    category: "tech",
    official: false,
    summary: "Still useful for hearing about crashes, queues and closed roads from other drivers.",
    why: "CB radio is less common than it was, but in parts of Europe, at ports and on long motorway runs, drivers still use it to share news of crashes, police checks and queues. It works where there's no phone signal.",
    lookFor: [
      "UK and EU multi-standard (switchable between countries)",
      "Works on 12V and 24V",
      "A magnetic aerial is easiest to fit",
    ],
    qty: () => "1 per cab, optional",
    query: "CB radio multi standard 12v 24v",
  },
  {
    id: "jumpstarter",
    name: "12/24V jump starter",
    category: "tech",
    official: false,
    summary: "Restart the truck after a cold night with the heater on, without waiting for a rescue.",
    why: "Night heaters, fridges and inverters can flatten the batteries overnight, especially in winter. A jump starter rated for 24V systems gets you going without waiting hours for breakdown cover.",
    lookFor: [
      "Clearly rated for 24V vehicles, not just 12V cars",
      "At least 3000A peak for large diesel engines",
      "Keep it charged: top it up every month",
    ],
    qty: () => "1 per cab",
    query: "24v jump starter truck lithium",
  },

  // ---- Load & cab security -------------------------------------------------
  {
    id: "padlock",
    name: "High-security trailer padlock",
    category: "security",
    official: false,
    summary: "Slows thieves down and helps prevent people getting into the trailer at ports.",
    why: "Load theft from parked trailers is common, and on routes to the UK you can be fined up to £10,000 for each person found hidden in your vehicle if you can't show you secured and checked it properly. A strong padlock on the rear doors is a basic step.",
    lookFor: [
      "A closed-shackle or shrouded padlock that's hard to cut",
      "Sold Secure or CEN security rated",
      "Weatherproof, with spare keys kept separately",
    ],
    qty: () => "1 per trailer, plus a spare",
    query: "high security closed shackle padlock weatherproof",
  },
  {
    id: "seals",
    name: "Numbered security seals",
    category: "security",
    official: false,
    summary: "Show that the doors haven't been opened since you loaded and checked.",
    why: "Numbered seals on the rear doors and any TIR cord let you prove the load hasn't been tampered with. Record the seal number on your vehicle checklist, and check it every time you stop.",
    lookFor: [
      "Uniquely numbered plastic or bolt seals",
      "Bolt seals are stronger for container and high-value loads",
      "Keep a written log of seal numbers and checks",
    ],
    qty: () => "A pack of 100",
    query: "numbered security seals pull tight",
  },
  {
    id: "doorstrap",
    name: "Cab door security strap",
    category: "security",
    official: false,
    summary: "Ties both cab doors together from the inside while you sleep.",
    why: "Thieves at parking areas sometimes break into cabs at night, while the driver is asleep. A heavy-duty strap or bar linking the two door handles from the inside means the doors can't be opened from outside, even if the lock is forced.",
    lookFor: [
      "A strap or bar that fits your cab's door handles",
      "Quick to release from the inside in an emergency",
      "Use it with the doors locked, not instead",
    ],
    qty: () => "1 per sleeper cab",
    showWhen: (h) => h.nights > 0,
    query: "truck cab door security strap",
  },
  {
    id: "ratchet",
    name: "Ratchet straps",
    category: "security",
    official: false,
    summary: "Spare straps for securing loads that have shifted, or loads that weren't secured properly.",
    why: "Load security is the driver's responsibility, and a load that shifts can tip the trailer or fall into the road. DVSA can stop you and issue fines if your load isn't secure. Keep a few spare straps even if the trailer has its own.",
    lookFor: [
      "EN 12195-2 rated, with the lashing capacity printed on the label",
      "50mm straps for most curtainsider loads",
      "Replace any that are cut, frayed or have damaged ratchets",
    ],
    qty: () => "4–6 straps",
    query: "ratchet straps 50mm EN 12195-2",
  },

  // ---- Driving in Europe ---------------------------------------------------
  {
    id: "docwallet",
    name: "Tacho card and document wallet",
    category: "europe",
    official: false,
    summary: "Keep your licence, CPC card, tacho card and passport together and dry.",
    why: "At a roadside check you'll be asked for your driving licence, Driver CPC card, tachograph card and printouts, passport and the vehicle and load documents (such as CMR notes). A dedicated wallet keeps them together. If you drive in the EU, carry your UK GHIC health card too.",
    lookFor: [
      "Slots for licence, CPC card and tacho card",
      "A zipped A4 section for CMR notes and vehicle papers",
      "Spare tachograph printer rolls in the cab",
    ],
    qty: (h) => each(h, "wallet", "wallets"),
    showWhen: (h) => h.europe,
    query: "tachograph card holder document wallet",
  },
  {
    id: "ukSticker",
    name: "UK sticker",
    category: "europe",
    official: true,
    summary: "GB stickers are no longer valid. You may need a UK sticker on the truck and trailer.",
    why: "Since September 2021, UK vehicles abroad need a UK sticker unless the number plate already shows the UK identifier. In Spain, Cyprus and Malta you need a sticker whatever your plate says. The old GB sticker must be covered or removed.",
    lookFor: [
      "White oval sticker with 'UK' in black letters",
      "One for the tractor unit and one for the trailer, if needed",
      "Remove or cover any old GB stickers",
    ],
    qty: () => "1 per unit and trailer",
    showWhen: (h) => h.europe,
    query: "UK sticker vehicle oval",
  },
  {
    id: "deflectors",
    name: "Headlamp beam deflectors",
    category: "europe",
    official: true,
    summary: "Stop UK headlights dazzling drivers on the right-hand side of the road.",
    why: "UK headlights are angled towards the left kerb, so on the continent they shine into oncoming drivers' eyes. You need to adjust them, either with stick-on deflectors or the vehicle's own settings. Many newer trucks can switch beam pattern in the menu; check the handbook first.",
    lookFor: [
      "Check whether your truck can switch beam pattern electronically first",
      "Deflectors that suit your headlamp type (LED, xenon or halogen)",
      "Remove them when you're back in the UK",
    ],
    qty: () => "1 set per unit, if your headlights can't be adjusted",
    showWhen: (h) => h.europe,
    query: "headlamp beam deflectors universal",
  },
  {
    id: "blindspot",
    name: "French blind spot stickers",
    category: "europe",
    official: true,
    summary: "France requires 'angles morts' stickers on vehicles over 3.5 tonnes.",
    why: "Since 2021, all vehicles over 3.5 tonnes driving in France must show official blind spot warning stickers on both sides and the back, to warn cyclists and pedestrians. Foreign trucks need them too, and you can be fined without them.",
    lookFor: [
      "The official French 'angles morts' design",
      "A set of at least 3: both sides and the rear (of the trailer if towing)",
      "Fit them between 0.9m and 1.5m from the ground",
    ],
    qty: () => "1 set per unit and trailer",
    showWhen: (h) => h.europe,
    query: "angles morts sticker truck France",
  },
  {
    id: "breathalyser",
    name: "Single-use breathalysers",
    category: "europe",
    official: false,
    summary: "French law still says drivers should carry one, although the fine was dropped.",
    why: "France's rules say every driver should carry a breathalyser, though there's no fine if you don't. They're cheap, and useful if you're not sure whether you're safe to drive the morning after. Remember professional drivers in many countries have a lower or zero alcohol limit.",
    lookFor: ["NF-certified single-use breathalysers", "Check the expiry date, they don't last forever"],
    qty: () => "A 2-pack per cab",
    showWhen: (h) => h.europe,
    query: "NF approved breathalyser France twin pack",
  },
  {
    id: "bulbkit",
    name: "Spare bulb and fuse kit",
    category: "europe",
    official: false,
    summary: "A blown bulb can get you stopped. Some countries recommend carrying spares.",
    why: "A failed light is an easy reason for police or DVSA to stop you. Many drivers carry spare 24V bulbs and fuses, and some countries recommend it. It doesn't help with LED lights, which need the whole unit replacing.",
    lookFor: ["24V bulbs for your unit's headlights, indicators and stop lights", "A selection of blade fuses"],
    qty: () => "1 kit per unit",
    showWhen: (h) => h.europe,
    query: "24v truck bulb kit fuses",
  },
  {
    id: "critair",
    name: "Crit'Air sticker (France)",
    category: "europe",
    official: true,
    summary: "Needed to drive in low-emission zones in French cities. Buy it only from the official site.",
    why: "Lyon, Paris, Grenoble and other French cities have low-emission zones where trucks need a Crit'Air clean air sticker. Order it in advance, because it's posted to your address. Many websites resell the sticker for several times the price, so use the official French government site.",
    lookFor: [
      "Order from certificat-air.gouv.fr, the official site",
      "You'll need a scan of the vehicle registration document",
      "Allow a few weeks for it to arrive",
    ],
    qty: () => "1 per vehicle",
    showWhen: (h) => h.europe,
    noBuy: "Not sold on Amazon. Order it only from the official French government site, certificat-air.gouv.fr.",
  },

  // ---- Winter --------------------------------------------------------------
  {
    id: "snowchains",
    name: "Truck snow chains",
    category: "winter",
    official: true,
    summary: "Required in winter in parts of Europe, including Austria and the French mountains.",
    why: "Austria requires trucks over 3.5 tonnes to carry snow chains from 1 November to 15 April, and mountain areas of France and Italy have similar winter rules. You can be fined or turned back without them. Practise fitting them at the yard before you need them in the dark.",
    lookFor: [
      "The exact size for your drive axle tyres (for example 315/80 R22.5)",
      "Chains for at least two drive wheels",
      "Gloves, a kneeling mat and a head torch for fitting them",
    ],
    qty: () => "1 pair for the drive axle",
    showWhen: (h) => h.winter,
    query: "snow chains 315/80 R22.5 truck",
  },
  {
    id: "scraper",
    name: "Ice scraper and de-icer",
    category: "winter",
    official: false,
    summary: "A truck windscreen is huge. Clear it properly before you set off.",
    why: "You must have a clear view through every window before driving. Clearing a truck windscreen and mirrors with a credit card takes forever. A long-handled scraper with a brush and a can of de-icer gets you moving faster on a frosty morning.",
    lookFor: [
      "A long handle to reach the middle of the screen",
      "A brush on the other end for snow",
      "Large cans of de-icer, kept in the cab, not the locker",
    ],
    qty: () => "1 scraper and 2 cans of de-icer",
    showWhen: (h) => h.winter,
    query: "long handle ice scraper snow brush",
  },
  {
    id: "handwarmers",
    name: "Hand warmers",
    category: "winter",
    official: false,
    summary: "Help on long waits in the cold, at ports, borders or a breakdown with no heater.",
    why: "If you break down or the night heater fails, the cab gets cold quickly. Air-activated hand warmers last up to 10 hours and take up no space. Keep a box in the cab all winter.",
    lookFor: ["Air-activated, up to 10 hours each", "Toe warmers for long cold spells outside", "Don't put them directly against your skin"],
    qty: () => "1 box of 40 pairs",
    showWhen: (h) => h.winter,
    query: "hand warmers disposable 40 pairs",
  },
  {
    id: "jacket",
    name: "Waterproof work jacket",
    category: "winter",
    official: false,
    summary: "For walk-round checks, sheeting and coupling up in the rain and cold.",
    why: "You spend more time outside the cab than people think. A waterproof, breathable jacket, ideally hi-vis, keeps you dry during checks and deliveries so you're not driving for hours in damp clothes.",
    lookFor: [
      "Waterproof and breathable, with a hood that fits over a cap",
      "Hi-vis versions work for sites that require it",
      "Waterproof over-trousers for heavy rain",
    ],
    qty: (h) => each(h, "jacket", "jackets"),
    showWhen: (h) => h.winter,
    query: "hi vis waterproof work jacket",
  },
  {
    id: "socks",
    name: "Thermal work socks",
    category: "winter",
    official: false,
    summary: "Cushioned socks for long days in safety boots, warm enough for frosty yards.",
    why: "Cold, damp feet in steel-toe boots make for a miserable shift. Thick, cushioned thermal socks help, and a spare pair to change into halfway through a long day helps even more.",
    lookFor: ["Wool blend, cushioned at the heel and toe", "Pack of several pairs, so you always have a dry pair"],
    qty: (h) => `${plural(days(h) * h.drivers, "pair", "pairs")}`,
    showWhen: (h) => h.winter,
    query: "thermal work socks men pack",
  },

  // ---- Health & comfort ----------------------------------------------------
  {
    id: "sunglasses",
    name: "Polarised driving sunglasses",
    category: "health",
    official: false,
    summary: "Cut glare from wet roads and low winter sun. You sit higher and see more of it.",
    why: "Low sun and glare off wet roads are tiring and dangerous. Polarised lenses cut reflected glare. Choose lenses suitable for driving, and never wear very dark lenses at dusk.",
    lookFor: [
      "Polarised, category 2 or 3 lenses (category 4 isn't legal for driving)",
      "Wraparound frames to block sun from the side",
      "Prescription clip-ons if you wear glasses",
    ],
    qty: (h) => each(h, "pair", "pairs"),
    query: "polarised driving sunglasses men category 3",
  },
  {
    id: "seatcushion",
    name: "Lumbar support cushion",
    category: "health",
    official: false,
    summary: "Back pain is one of the most common problems for professional drivers.",
    why: "Hours in the seat every day put strain on your lower back. A memory foam lumbar cushion helps you sit properly, especially in older trucks with worn seats. Get out and walk around on every break, too.",
    lookFor: [
      "Memory foam with an adjustable strap to hold it in place",
      "Breathable, washable cover",
      "Adjust your seat and mirrors properly first",
    ],
    qty: (h) => each(h, "cushion", "cushions"),
    query: "memory foam lumbar support cushion car seat",
  },
  {
    id: "medication",
    name: "Pill organiser and travel medicine kit",
    category: "health",
    official: false,
    summary: "Keep regular medication, painkillers and indigestion tablets organised for the trip.",
    why: "If you take regular medication, a weekly pill organiser makes it easy to keep track on the road. Add painkillers, antihistamines and indigestion remedies, but check that nothing you take causes drowsiness: driving while impaired by medicine is an offence.",
    lookFor: [
      "A 7-day pill organiser",
      "Check every medicine's label for drowsiness warnings",
      "Carry enough regular medication for a few extra days, in case you're delayed",
    ],
    qty: (h) => each(h, "kit", "kits"),
    query: "7 day pill organiser",
  },
];

function amazonUrl(product) {
  if (product.noBuy) return null;
  const tag = encodeURIComponent(AMAZON_TAG);
  if (product.asin) return `https://www.amazon.co.uk/dp/${product.asin}?tag=${tag}`;
  return `https://www.amazon.co.uk/s?k=${encodeURIComponent(product.query)}&tag=${tag}`;
}

// The 10 items every truck driver should have, shown first under "Start here".
const ESSENTIALS = ["hivis", "boots", "gloves", "headtorch", "firstaid", "satnav", "dashcam", "coolbox", "flask", "charger"];

const SITUATIONS = [
  { photo: "nightsout", title: "Nights out", text: "Sleep, eat and wash in the cab", filter: "cab" },
  { photo: "europe", title: "Driving in Europe", text: "The kit the law asks for abroad", filter: "europe" },
  { photo: "winter", title: "Winter routes", text: "Snow chains, ice and cold nights", filter: "winter" },
  { photo: "motorway", title: "Long days on the road", text: "Stay fed, rested and comfortable", filter: "food" },
  { photo: "loading", title: "Yards & deliveries", text: "PPE that gets you through the gate", filter: "safety" },
  { photo: "security", title: "Load & cab security", text: "Protect yourself, the cab and the load", filter: "security" },
];
